// One-shot generator for app/components/claim-geo.js: the city locations of
// the people who claimed names, resolved from the public `location` field on
// each owner's GitHub profile via the Open-Meteo geocoding API (free, no
// key). The registry itself stores nothing about location, so this is the
// only honest source, and it stays honest by being committed: the stats page
// counts from this file at build time, refresh by re-running the script.
//
//   REGISTRY_TOKEN=<gh token> node scripts/geocode-owners.mjs
//
// Unresolvable locations (blank, jokes, geocoder misses) are counted and
// logged, never guessed.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DELAY_MS = 120;

const readEnv = () => {
  try {
    const m = readFileSync('.env.local', 'utf8').match(/^REGISTRY_TOKEN=(.+)$/m);
    if (m) return m[1].trim();
  } catch {}
  return process.env.REGISTRY_TOKEN ?? '';
};
const token = readEnv();

const dir = join(process.cwd(), 'domains');
const logins = readdirSync(dir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')).owner?.github)
  .filter(Boolean);
const unique = [...new Set(logins)];
console.log(`${logins.length} claims, ${unique.length} unique owners`);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function githubLocation(login) {
  try {
    const res = await fetch(`https://api.github.com/users/${login}`, {
      headers: {
        Accept: 'application/vnd.github+json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
    });
    if (!res.ok) return null;
    const body = await res.json();
    return body.location?.trim() || null;
  } catch {
    return null;
  }
}

// Free-text locations like "Chennai, India": try the full string first, then
// the leading segment (usually the city), then the trailing one (country).
async function geocode(place) {
  const tries = [place];
  const parts = place.split(',');
  if (parts.length > 1) tries.push(parts[0].trim(), parts.at(-1).trim());
  for (const q of tries) {
    if (!q || q.length < 2) continue;
    try {
      const url = `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`;
      const res = await fetch(url);
      if (!res.ok) continue;
      const body = await res.json();
      const hit = body.results?.[0];
      if (hit) return { lat: hit.latitude, lon: hit.longitude, label: `${hit.name}, ${hit.country ?? ''}`.replace(/, $/, '') };
    } catch {}
    await sleep(DELAY_MS);
  }
  return null;
}

const geoCache = new Map(); // location string -> geocoded or null
const out = {};
let resolved = 0;
let noLocation = 0;
let unresolvable = [];

for (let i = 0; i < unique.length; i++) {
  const login = unique[i];
  const place = await githubLocation(login);
  if (!place) {
    noLocation++;
    continue;
  }
  if (!geoCache.has(place)) {
    geoCache.set(place, await geocode(place));
    await sleep(DELAY_MS);
  }
  const hit = geoCache.get(place);
  if (hit) {
    out[login] = [hit.lat, hit.lon];
    resolved++;
  } else {
    unresolvable.push(place);
  }
  if ((i + 1) % 25 === 0) console.log(`  ${i + 1}/${unique.length} (resolved so far: ${resolved})`);
}

unresolvable = [...new Set(unresolvable)].slice(0, 20);
console.log(`resolved: ${resolved}, no location on profile: ${noLocation}, unresolvable: ${unique.length - resolved - noLocation}`);
if (unresolvable.length) console.log('sample unresolvable:', unresolvable.join(' | '));

const file = `// Generated by scripts/geocode-owners.mjs from the public location field
// on each owner's GitHub profile (Open-Meteo geocoding). Regenerate, do not
// hand-edit. Owners with a blank or unplaceable location are simply absent;
// GEO_RESOLVED/GEO_TOTAL keep the stats page honest about coverage.
export const CLAIM_GEO = ${JSON.stringify(out)};
export const GEO_RESOLVED = ${resolved};
export const GEO_TOTAL = ${unique.length};
`;
writeFileSync('app/components/claim-geo.js', file);
console.log(`wrote app/components/claim-geo.js (${(file.length / 1024).toFixed(1)} KB)`);
